#!/bin/sh
#
# Check other-packages/* control files
#

_usage()
{
    echo >&2 "Usage: $0 [options]"
    echo >&2 "Options:"
    echo >&2 "  -d           debug"
    echo >&2 "  -v           verbose (debugging)"
    echo >&2 "               second -v => also keep tmp.* files"
    exit 1
}

debug=false
verbose=false
very_verbose=false
while getopts 'dv?' p
do
    case "$p"
    in
	d)	debug=true
		;;

	v)	if $verbose
		then
		    very_verbose=true
		else
		    verbose=true
		fi
		;;

	?)	_usage
		# NOTREACHED
    esac
done
shift `expr $OPTIND - 1`
[ $# -ne 1 ] || _usage

sts=1		# failure is the default
if $very_verbose
then
    tmp=tmp
    rm -rf tmp
else
    tmp=${TMPDIR:-/tmp}/list-packages-$$
    trap "rm -rf $tmp.*; exit \$sts" 0 1 2 3 15
fi
mkdir -p $tmp || exit

here=pwd

rm -f $tmp/*
./old-list-packages -R || exit
mv tmp.* $tmp

# copied from post-setup ...
#
pkg_env=""
if which apt-get >/dev/null 2>&1
then
    pkg_type=dpkg
elif which zypper >/dev/null 2>&1
then
    pkg_type=rpm
elif which dnf >/dev/null 2>&1
then
    pkg_type=rpm
elif which yum >/dev/null 2>&1
then
    pkg_type=rpm
elif which pacman >/dev/null 2>&1
then
    pkg_type=pacman
elif which pkg >/dev/null 2>&1
then
    pkg_type="pkg"
# pkgin has to be before pkg_add in this compound
# if-elif-elif-else-fi because NetBSD has both and we need
# to use pkgin for NetBSD
#
elif which pkgin >/dev/null 2>&1
then
    pkg_type="pkgin"
elif which pkg_add >/dev/null 2>&1
then
    pkg_type="pkg_add"
else
    echo >&2 "Botch: need recipe for system package type"
    exit
fi
$debug && echo "Debug: package type: $pkg_type"

_find()
{
    # $1 needs to be an installed file, directory, symlink, ...
    #
    [ ! -e "$1" ] && return 1
    # now see if you can discover the package that installed $1
    #
    case "$pkg_type"
    in
	rpm)	# output like sed-4.9-7.fc44.x86_64
		#
		rpm -q -f "$1" | sed -e 's/-[0-9].*//'
		;;
	dpkg)	# output like sed: /usr/bin/sed
		#
		dpkg-query -S "$1" | sed -e 's/:.*//'
		;;
	*)
		echo >&2
		echo >&2 "Botch: _find: need recipe to find package for installed file for pkg_type=$pkg_type"
		return 1
		;;
    esac

    return 0
}

if [ -s $tmp/tmp.require ]
then
    echo "Warning: required packages? (this is not expected)"
    cat $tmp/tmp.require
else
    $verbose && echo "Warning: no required packages?"
fi

echo "Checking manifest ..."
# lines are like ...
#	git		[git or git-core] :172
#
sed <$tmp/tmp.manifest \
    -e 's/[ 	][ 	]*/ /g' \
    -e 's/^ //' \
    -e 's/([^)]*)//' \
    -e 's/ or / /g' \
    -e 's/[[]//' \
    -e 's/] :/ :/' \
    -e 's/\(.*\) :\([0-9]*[0-9]\)$/\2 \1/' \
| while read lineno target line
do
    $debug && echo lineno=$lineno target=$target line=$line
    case "$line"
    in
	N/A\ on\ *|N/A)	continue
			;;
	SKIP\ on\ *)	continue
			;;
    esac

    rm -f $tmp/match
    for pkg in $line
    do
	if grep "^$pkg\$" $tmp/tmp.allpkgs >$tmp/grep
	then
	    if [ "$pkg" = "`cat $tmp/grep`" ]
	    then
		$debug && echo "Debug: $pkg: exact match `cat $tmp/grep`"
	    else
		$debug && echo "Debug: $pkg: pattern match `cat $tmp/grep`"
	    fi
	    touch $tmp/match
	    break
	else
	    $debug && echo "Debug: manifest:$lineno $pkg ? `cat $tmp/grep`"
	fi
    done
    if [ ! -f $tmp/match ]
    then
	$debug && echo "$line: no package matches"
	for try in `echo "$target" | sed -e 's/|/ /g'`
	do
	    if _find "$try" >$tmp/find
	    then
		echo "mainfest:$lineno `cat $tmp/find` provides $try"
		touch $tmp/match
		break
	    elif which "$target" >/dev/null 2>&1
	    then
		if _find "`which $try`" >$tmp/find
		then
		    echo "mainfest:$lineno `cat $tmp/find` provides `which $try`"
		    touch $tmp/match
		    break
		fi
	    fi
	done
    fi
    if [ ! -f $tmp/match ]
    then
	echo "manifest:$lineno no packages match target=$target pkgs=$line"
    fi
done
